
export interface PaaSDeploymentLog {
  /**
   * Unique id of the log. Note that this field value is generated by elasticsearch. Should always be null before you write it to elastic search.
   */
  id: string;

  /**
   * Deployment id is unique for a deployment
   * It corresponds to {@link alien4cloud.model.deployment.Deployment#getId}
   * This field is mandatory
   */
  deploymentId: string;

  /**
   * Deployment PaaS id is unique for an application on a given environment (for ex : Alien-Prod)
   * It corresponds to {@link alien4cloud.model.deployment.Deployment#getOrchestratorDeploymentId}
   * This field is mandatory
   */
  deploymentPaaSId: string;

  /**
   * Log's level
   * This field is mandatory
   */
  level: PaaSDeploymentLogLevel;

  /**
   * The type of the log entry given by the PaaS
   * For cloudify it can be a4c_workflow_event, Task sent, Task started etc ...
   * For puccini it can be operation_output, operation_info, plugin, provider, general ...
   * This field is mandatory
   */
  type: string;

  /**
   * Log's timestamp
   * This field is mandatory
   */
  timestamp: number;

  /**
   * The timestamp raw value as it was provided by the orchestrator.
   */
  rawtimestamp: string;

  /**
   * Id of the workflow that generated the log
   * This field is optional
   */
  workflowId: string;

  /**
   * Id of the execution that generated the log
   * This field is optional
   */
  executionId: string;

  /**
   * Id of the task that generated the log
   * This field is optional
   */
  taskId: string;

  /**
   * Id of the node that generated the log
   * This field is optional
   */
  nodeId: string;

  /**
   * Id of the instance that generated the log
   * This field is optional
   */
  instanceId: string;

  /**
   * Interface on the node that generated the log
   * This field is optional
   */
  interfaceName: string;

  /**
   * Operation inside the interface on the node that generated the log
   * This field is optional
   */
  operationName: string;

  /**
   * Finally the log's content in free text
   * This field is mandatory
   */
  content: string;

}

export enum PaaSDeploymentLogLevel {
  DEBUG = "debug", INFO = "info", WARN = "warn", ERROR = "error"
}
