export enum DeploymentStatus {

  DEPLOYED = "DEPLOYED",
  UNDEPLOYED = "UNDEPLOYED",
  INIT_DEPLOYMENT = "INIT_DEPLOYMENT",
  DEPLOYMENT_IN_PROGRESS = "DEPLOYMENT_IN_PROGRESS",
  UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS",
  UPDATED = "UPDATED",
  UNDEPLOYMENT_IN_PROGRESS = "UNDEPLOYMENT_IN_PROGRESS",
  WARNING = "WARNING",
  FAILURE = "FAILURE",
  UPDATE_FAILURE = "FAILURE",
  UNKNOWN = "FAILURE"
}

