export enum EnvironmentType {
  OTHER = "OTHER", 
  DEVELOPMENT = "DEVELOPMENT", 
  INTEGRATION_TESTS = "INTEGRATION_TESTS" , 
  USER_ACCEPTANCE_TESTS = "USER_ACCEPTANCE_TESTS", 
  PRE_PRODUCTION = "PRE_PRODUCTION", 
  PRODUCTION = "PRODUCTION"
}
